/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author adnan
 */
public class ProfitSale extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form ProfitSale
     *
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws java.sql.SQLException
     */
    public ProfitSale() throws IOException, FileNotFoundException, SQLException {
        initComponents();
        conn = Java_Connect.conectrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        todatepayment1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        yeartext1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fromdatepayment1 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        paymenttypebox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nettradepricetext = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        netmrptext = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        netprofittext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        profitetbl = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Sale Profit ");

        jPanel1.setBackground(new java.awt.Color(67, 86, 86));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/submit.png"))); // NOI18N
        jButton5.setText("Submit");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        jButton6.setText("Report");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Year");

        todatepayment1.setDateFormatString("yyyy-MM-dd");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("To");

        yeartext1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yeartext1.setForeground(new java.awt.Color(102, 0, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("From");

        fromdatepayment1.setDateFormatString("yyyy-MM-dd");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Payment Type");

        paymenttypebox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paymenttypebox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cash", "Credit" }));
        paymenttypebox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                paymenttypebox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        paymenttypebox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttypebox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymenttypebox1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(fromdatepayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(todatepayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yeartext1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel12)
                                .addComponent(jLabel14)))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymenttypebox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(yeartext1)
                                .addComponent(fromdatepayment1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(todatepayment1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Net Trade Amount:");

        nettradepricetext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nettradepricetext.setForeground(new java.awt.Color(255, 255, 255));
        nettradepricetext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Net Sale Amount ");

        netmrptext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        netmrptext.setForeground(new java.awt.Color(255, 255, 255));
        netmrptext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Net Profit:");

        netprofittext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        netprofittext.setForeground(new java.awt.Color(255, 255, 255));
        netprofittext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nettradepricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netmrptext, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(netprofittext, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(netmrptext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(nettradepricetext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(netprofittext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        profitetbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        profitetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        profitetbl.setGridColor(new java.awt.Color(204, 204, 204));
        profitetbl.setRowHeight(30);
        jScrollPane2.setViewportView(profitetbl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1574, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        switch (paymenttypebox1.getSelectedIndex()) {
            case 0:
                break;
            case 1:
                try {
                    String sql = "Select "
                            + "invoiceNo as 'Invoice No',"
                            + "DATE_FORMAT(invoicedate,"
                            + "'%d-%m-%Y') as 'Invoice Date',"
                            + "TotalAmount as 'Total Amount',"
                            + "netdiscount as 'Total Descount',"
                            + "TotalVat as 'Vat(5%)',"
                            + "totaltraprice as 'Total Trade Price',"
                            + "totalprofite as 'Net Profit' from cashsale cl where cl.invoicedate BETWEEN ? AND ? OR year(cl.invoicedate)='" + yeartext1.getText() + "'";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment1.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment1.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    profitetbl.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(totaltraprice) as 'nettradeprice',sum(TotalAmount) as 'netmrpprice' ,sum(totalprofite) as 'netprofite' from cashsale where invoicedate BETWEEN ? AND ? OR year(invoicedate)='" + yeartext1.getText() + "'";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment1.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment1.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        double nettradeprice = rs.getDouble("nettradeprice");
                        nettradepricetext.setText(String.format("%.2f", nettradeprice));

                        double netmrpprice = rs.getDouble("netmrpprice");
                        netmrptext.setText(String.format("%.2f", netmrpprice));
                        double netprofite = rs.getDouble("netprofite");
                        netprofittext.setText(String.format("%.2f", netprofite));
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                break;
            case 2:
                try {
                    String sql = "Select invoiceNo as 'Invoice No',DATE_FORMAT(invoicedate, '%d-%m-%Y') as 'Invoice Date',TotalAmount as 'Total Amount', netdiscount as 'Total Descount', TotalVat as 'Vat(5%)',totaltraprice as 'Total Trade Price',totalprofite as 'Net Profit' from sale cl where cl.invoicedate BETWEEN ? AND ? OR year(cl.invoicedate)='" + yeartext1.getText() + "'";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment1.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment1.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    profitetbl.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(totaltraprice) as 'nettradeprice',sum(TotalAmount) as 'netmrpprice' ,sum(totalprofite) as 'netprofite' from sale where invoicedate BETWEEN ? AND ? OR year(invoicedate)='" + yeartext1.getText() + "'";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment1.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment1.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        double nettradeprice = rs.getDouble("nettradeprice");
                        nettradepricetext.setText(String.format("%.2f", nettradeprice));

                        double netmrpprice = rs.getDouble("netmrpprice");
                        netmrptext.setText(String.format("%.2f", netmrpprice));
                        double netprofite = rs.getDouble("netprofite");
                        netprofittext.setText(String.format("%.2f", netprofite));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                break;
            default:
                break;
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (((JTextField) fromdatepayment1.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) todatepayment1.getDateEditor().getUiComponent()).getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fillup Date Filed");
        } else {
            switch (paymenttypebox1.getSelectedIndex()) {
                case 0:
                    JOptionPane.showMessageDialog(null, "Please Select Payment Type");
                    break;
                case 1:
                    try {
                        
                        String fromdate = ((JTextField) fromdatepayment1.getDateEditor().getUiComponent()).getText();
                        String todate = ((JTextField) todatepayment1.getDateEditor().getUiComponent()).getText();

                        JasperDesign jd = JRXmlLoader.load(new File("")
                                .getAbsolutePath()
                                + "/src/Report/Cashsaleprofit.jrxml");
                        HashMap para = new HashMap();
                        para.put("fromdate", fromdate);
                        para.put("todate", todate);
                        para.put("year", yeartext1.getText());
                        JasperReport jr = JasperCompileManager.compileReport(jd);
                        JasperPrint jp = JasperFillManager.fillReport(jr, para, conn);
                        JasperViewer.viewReport(jp, false);

                    } catch (NumberFormatException | JRException ex) {

                        JOptionPane.showMessageDialog(null, ex);

                    }
                    break;
                case 2:
                    try {

                        //  int total = Integer.parseInt(AllTotalText.getText());
                        //String inwords = convert(total) + " Tk only";
                        String fromdate = ((JTextField) fromdatepayment1.getDateEditor().getUiComponent()).getText();
                        String todate = ((JTextField) todatepayment1.getDateEditor().getUiComponent()).getText();

                        JasperDesign jd = JRXmlLoader.load(new File("")
                                .getAbsolutePath()
                                + "/src/Report/Creditsaleprofit.jrxml");
                        //    JasperDesign jd = JRXmlLoader.load("C:\\Users\\adnan\\Documents\\NetBeansProjects\\MobileInvoice\\src\\Riport\\voiceriport.jrxml");

                        HashMap para = new HashMap();
                        para.put("fromdate", fromdate);
                        para.put("todate", todate);
                        para.put("year", yeartext1.getText());
                        JasperReport jr = JasperCompileManager.compileReport(jd);
                        JasperPrint jp = JasperFillManager.fillReport(jr, para, conn);
                        JasperViewer.viewReport(jp, false);

                    } catch (NumberFormatException | JRException ex) {

                        JOptionPane.showMessageDialog(null, ex);

                    }
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Make Condition Perfectly");
                    break;
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void paymenttypebox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_paymenttypebox1PopupMenuWillBecomeInvisible
        switch (paymenttypebox1.getSelectedIndex()) {
            case 0:
                break;
            case 1:
                try {
                    String sql = "Select "
                            + "invoiceNo as 'Invoice No',"
                            + "DATE_FORMAT(invoicedate, '%d-%m-%Y') as 'Invoice Date',"
                            + "TotalAmount as 'Total Amount',"
                            + "netdiscount as 'Total Descount',"
                            + "TotalVat as 'Vat',"
                            + "totaltraprice as 'Total Trade Price',"
                            + "totalprofite as 'Net Profit' from cashsale cl ";
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    profitetbl.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(totaltraprice) as 'nettradeprice',sum(TotalAmount) as 'netmrpprice' ,sum(totalprofite) as 'netprofite' from cashsale";
                    pst = conn.prepareStatement(sql);

                    rs = pst.executeQuery();
                    if (rs.next()) {
                        double nettradeprice = rs.getDouble("nettradeprice");
                        nettradepricetext.setText(String.format("%.2f", nettradeprice));
                        double netmrpprice = rs.getDouble("netmrpprice");
                        netmrptext.setText(String.format("%.2f", netmrpprice));
                        double netprofite = rs.getDouble("netprofite");
                        netprofittext.setText(String.format("%.2f", netprofite));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                break;
            case 2:
                try {
                    String sql = "Select invoiceNo as 'Invoice No',DATE_FORMAT(invoicedate, '%d-%m-%Y') as 'Invoice Date',TotalAmount as 'Total Amount', netdiscount as 'Total Descount', TotalVat as 'Vat(5%)',totaltraprice as 'Total Trade Price',totalprofite as 'Net Profit' from sale cl ";
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    profitetbl.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(totaltraprice) as 'nettradeprice',sum(TotalAmount) as 'netmrpprice' ,sum(totalprofite) as 'netprofite' from sale";
                    pst = conn.prepareStatement(sql);

                    rs = pst.executeQuery();
                    if (rs.next()) {
                        double nettradeprice = rs.getDouble("nettradeprice");
                        nettradepricetext.setText(String.format("%.2f", nettradeprice));
                        double netmrpprice = rs.getDouble("netmrpprice");
                        netmrptext.setText(String.format("%.2f", netmrpprice));
                        double netprofite = rs.getDouble("netprofite");
                        netprofittext.setText(String.format("%.2f", netprofite));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                break;
            default:
                break;
        }

    }//GEN-LAST:event_paymenttypebox1PopupMenuWillBecomeInvisible

    private void paymenttypebox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttypebox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymenttypebox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fromdatepayment1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel netmrptext;
    private javax.swing.JLabel netprofittext;
    private javax.swing.JLabel nettradepricetext;
    private javax.swing.JComboBox<String> paymenttypebox1;
    private javax.swing.JTable profitetbl;
    private com.toedter.calendar.JDateChooser todatepayment1;
    private javax.swing.JTextField yeartext1;
    // End of variables declaration//GEN-END:variables
}
