/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adnan
 */
public class StarNumber extends javax.swing.JInternalFrame {
 Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int confirmnmbercash;
     int confirmnmbercredit;
     int importconfirm;
     int exportconfirm;
    /**
     * Creates new form StarNumber
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public StarNumber() throws SQLException, IOException {
        initComponents();
        conn = Java_Connect.conectrDB();
        cashnumber();
        creditumber();
        importnumber();
        exportnumber();
        
        cashbtn.setEnabled(false);
        creditbtn.setEnabled(false);
        importbtn.setEnabled(false);
        exportbtn.setEnabled(false);
    }
   private void cashnumber() throws SQLException {

        try {
            String sql = "Select number	 from numberformat where id=1";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()) {

                int name = rs.getInt("number");
                
                String gpper = String.format("%d", name);
               cashinvoicetext.setText(gpper);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
   
      private void creditumber() throws SQLException {

        try {
            String sql = "Select number	 from numberformat where id=2";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()) {

                int name = rs.getInt("number");
                 String gpper = String.format("%d", name);
               creditnumbertext.setText(gpper);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
      
         private void  importnumber() throws SQLException {

        try {
            String sql = "Select number	 from numberformat where id=3";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()) {

                int name = rs.getInt("number");
                  String gpper = String.format("%d", name);
               importnumber.setText(gpper);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }}
        
               private void  exportnumber() throws SQLException {

        try {
            String sql = "Select number	 from numberformat where id=4";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()) {

                int name = rs.getInt("number");
                  String gpper = String.format("%d", name);
               exportnumber.setText(gpper);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cashinvoicetext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        creditnumbertext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        importnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        exportnumber = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        importbtn = new javax.swing.JButton();
        exportbtn = new javax.swing.JButton();
        creditbtn = new javax.swing.JButton();
        cashbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Number Format");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cash Invoice");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, 29));

        cashinvoicetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cashinvoicetext.setBorder(null);
        cashinvoicetext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashinvoicetextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashinvoicetextKeyTyped(evt);
            }
        });
        getContentPane().add(cashinvoicetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 30, 210, 29));

        jLabel2.setText("Credit Invoice");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 70, -1, 29));

        creditnumbertext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        creditnumbertext.setBorder(null);
        getContentPane().add(creditnumbertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 70, 211, 29));

        jLabel3.setText("Import");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 110, -1, 29));

        importnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        importnumber.setBorder(null);
        getContentPane().add(importnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 110, 211, 29));

        jLabel5.setText("Export");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, 29));

        exportnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exportnumber.setBorder(null);
        getContentPane().add(exportnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 211, 29));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("[* This Only Open When Required System Database Empty, Otherwise Fail To Execution ]");

        jLabel7.setText("Inventory Execution(Apply Only First Time Or Start To Use This Software)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 239, -1, -1));

        importbtn.setBackground(new java.awt.Color(204, 0, 0));
        importbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        importbtn.setForeground(new java.awt.Color(255, 255, 255));
        importbtn.setText("Execution");
        importbtn.setBorder(null);
        importbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importbtnActionPerformed(evt);
            }
        });

        exportbtn.setBackground(new java.awt.Color(204, 0, 0));
        exportbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exportbtn.setForeground(new java.awt.Color(255, 255, 255));
        exportbtn.setText("Execution");
        exportbtn.setBorder(null);
        exportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportbtnActionPerformed(evt);
            }
        });

        creditbtn.setBackground(new java.awt.Color(204, 0, 0));
        creditbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        creditbtn.setForeground(new java.awt.Color(255, 255, 255));
        creditbtn.setText("Execution");
        creditbtn.setBorder(null);
        creditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditbtnActionPerformed(evt);
            }
        });

        cashbtn.setBackground(new java.awt.Color(204, 0, 0));
        cashbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cashbtn.setForeground(new java.awt.Color(255, 255, 255));
        cashbtn.setText("Execution");
        cashbtn.setBorder(null);
        cashbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cashbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(importbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(creditbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creditbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 22, 139, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Check");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 102, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Check");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Check");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 22, 115, -1));

        setBounds(350, 50, 626, 382);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
            String sql = "Select invoiceNo from cashsale";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {

               JOptionPane.showMessageDialog(null, "*The Cash Invoice database Already Contain The Data, Please Make sure this database is Empty ");
               
               cashbtn.setEnabled(false);
               cashnumber();
            }
            
            else{
             JOptionPane.showMessageDialog(null, "Successfully Check! You Can Add A start Format Invoice Number By click Execution Button");
            cashbtn.setEnabled(true);
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cashinvoicetextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashinvoicetextKeyTyped
       
    }//GEN-LAST:event_cashinvoicetextKeyTyped

    private void cashinvoicetextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashinvoicetextKeyReleased
    
    }//GEN-LAST:event_cashinvoicetextKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
            String sql = "Select invoiceNo from sale";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {

               JOptionPane.showMessageDialog(null, "*The Cash Invoice database Already Contain The Data, Please Make sure this database is Empty ");
               
               creditbtn.setEnabled(false);
            }
            
            else{
             JOptionPane.showMessageDialog(null, "Successfully Check! You Can Add A start Format Invoice Number By click Execution Button");
            creditbtn.setEnabled(true);
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String sql = "Select importCode from import";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {

               JOptionPane.showMessageDialog(null, "*The Cash Invoice database Already Contain The Data, Please Make sure this database is Empty ");
               
               importbtn.setEnabled(false);
            }
            
            else{
             JOptionPane.showMessageDialog(null, "Successfully Check! You Can Add A start Format Invoice Number By click Execution Button");
            importbtn.setEnabled(true);
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          try {
            String sql = "Select exportCode from export";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {

               JOptionPane.showMessageDialog(null, "*The Cash Invoice database Already Contain The Data, Please Make sure this database is Empty ");
               
               exportbtn.setEnabled(false);
            }
            
            else{
             JOptionPane.showMessageDialog(null, "Successfully Check! You Can Add A start Format Invoice Number By click Execution Button");
            exportbtn.setEnabled(true);
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        } 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void cashbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashbtnActionPerformed
 try {
            String sql = "Select invoiceNo from cashsale";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {
               
               cashbtn.setEnabled(false);
               confirmnmbercash=0;
                cashnumber();
            }
            
            else{
             
           // cashbtn.setEnabled(true);
            confirmnmbercash=1;
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }         
        
        if(confirmnmbercash==1){
        try {

            int id = 1;

            String sql = "Update numberformat set number='" + cashinvoicetext.getText() + "' where id='" + id + "'";
            pst = conn.prepareStatement(sql);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Succefull Execution");
             cashbtn.setEnabled(false);

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
     try {
         cashnumber();
     } catch (SQLException ex) {
         Logger.getLogger(StarNumber.class.getName()).log(Level.SEVERE, null, ex);
     }
        }
    
    }//GEN-LAST:event_cashbtnActionPerformed

    private void creditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditbtnActionPerformed
       try {
            String sql = "Select invoiceNo from sale";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {
               
               creditbtn.setEnabled(false);
               confirmnmbercredit=0;
                cashnumber();
            }
            
            else{
             
           // cashbtn.setEnabled(true);
            confirmnmbercredit=1;
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }         
        
        if(confirmnmbercredit==1){
        try {

            int id = 2;

            String sql = "Update numberformat set number='" + creditnumbertext.getText() + "' where id='" + id + "'";
            pst = conn.prepareStatement(sql);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Succefull Execution");
             creditbtn.setEnabled(false);

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
     try {
         creditumber();
     } catch (SQLException ex) {
         Logger.getLogger(StarNumber.class.getName()).log(Level.SEVERE, null, ex);
     }
        }
    }//GEN-LAST:event_creditbtnActionPerformed

    private void importbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importbtnActionPerformed
             try {
            String sql = "Select importCode from import";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {
               
               importbtn.setEnabled(false);
               importconfirm=0;
                cashnumber();
            }
            
            else{
             
           // cashbtn.setEnabled(true);
            importconfirm=1;
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }         
        
        if(importconfirm==1){
        try {

            int id = 3;

            String sql = "Update numberformat set number='" + importnumber.getText() + "' where id='" + id + "'";
            pst = conn.prepareStatement(sql);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Succefull Execution");
             importbtn.setEnabled(false);

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
     try {
         importnumber();
     } catch (SQLException ex) {
         Logger.getLogger(StarNumber.class.getName()).log(Level.SEVERE, null, ex);
     }
        }
    }//GEN-LAST:event_importbtnActionPerformed

    private void exportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportbtnActionPerformed
                    try {
            String sql = "Select exportCode from export";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tbl_employeeinfo.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()==true) {
               
               exportbtn.setEnabled(false);
               exportconfirm=0;
                cashnumber();
            }
            
            else{
             
           // cashbtn.setEnabled(true);
            exportconfirm=1;
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }         
        
        if(exportconfirm==1){
        try {

            int id = 2;

            String sql = "Update numberformat set number='" + exportnumber.getText() + "' where id='" + id + "'";
            pst = conn.prepareStatement(sql);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Succefull Execution");
             exportbtn.setEnabled(false);

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
     try {
        exportnumber();
     } catch (SQLException ex) {
         Logger.getLogger(StarNumber.class.getName()).log(Level.SEVERE, null, ex);
     }
        }
    }//GEN-LAST:event_exportbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashbtn;
    private javax.swing.JTextField cashinvoicetext;
    private javax.swing.JButton creditbtn;
    private javax.swing.JTextField creditnumbertext;
    private javax.swing.JButton exportbtn;
    private javax.swing.JTextField exportnumber;
    private javax.swing.JButton importbtn;
    private javax.swing.JTextField importnumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
