/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author adnan
 */
public class VatCollection extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String description;

    /**
     * Creates new form VatCollection
     *
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public VatCollection() throws SQLException, IOException {
        initComponents();
        conn = Java_Connect.conectrDB();
        // table_update();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fromdatepayment = new com.toedter.calendar.JDateChooser();
        todatepayment = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        typebox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        totalvattext = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalamnt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        netotaltext = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        discountext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Vat Info");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/source/company.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(67, 86, 86));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From");

        fromdatepayment.setDateFormatString("yyyy-MM-dd");

        todatepayment.setDateFormatString("yyyy-MM-dd");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To");

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Statement");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Type");

        typebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Invoice" }));
        typebox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                typeboxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typebox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromdatepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(todatepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typebox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(todatepayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fromdatepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Vat:");

        totalvattext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totalvattext.setForeground(new java.awt.Color(255, 255, 255));
        totalvattext.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalvattext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 1, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Amount:");

        totalamnt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totalamnt.setForeground(new java.awt.Color(255, 255, 255));
        totalamnt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalamnt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 1, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Net Total");

        netotaltext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        netotaltext.setForeground(new java.awt.Color(255, 255, 255));
        netotaltext.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netotaltext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 1, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Discount");

        discountext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        discountext.setForeground(new java.awt.Color(255, 255, 255));
        discountext.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        discountext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalamnt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discountext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalvattext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(netotaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(673, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalamnt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netotaltext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalvattext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        datatbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datatbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SI No", "Invoice/Purchase No", "Input Date", "Customer/Supplier Info", "Amount", "Discount", "Vat", "Net Total", "Invoice Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        datatbl.setGridColor(new java.awt.Color(204, 204, 204));
        datatbl.setRowHeight(30);
        jScrollPane1.setViewportView(datatbl);
        if (datatbl.getColumnModel().getColumnCount() > 0) {
            datatbl.getColumnModel().getColumn(0).setResizable(false);
            datatbl.getColumnModel().getColumn(0).setPreferredWidth(30);
            datatbl.getColumnModel().getColumn(1).setResizable(false);
            datatbl.getColumnModel().getColumn(2).setResizable(false);
            datatbl.getColumnModel().getColumn(3).setResizable(false);
            datatbl.getColumnModel().getColumn(3).setPreferredWidth(300);
            datatbl.getColumnModel().getColumn(4).setResizable(false);
            datatbl.getColumnModel().getColumn(5).setResizable(false);
            datatbl.getColumnModel().getColumn(6).setResizable(false);
            datatbl.getColumnModel().getColumn(7).setResizable(false);
            datatbl.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(70, 10, 1291, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (typebox.getSelectedIndex()) {
            case 1:
                try {
                    int tree = 0;
                    DefaultTableModel model2 = (DefaultTableModel) datatbl.getModel();
                    model2.setRowCount(0);
                    String sql = "Select invoiceNopurchaseNo as 'InvoiceNo',DATE_FORMAT(invoicedate, '%d-%m-%Y') as 'InvoiceDate',(select customername from customerinfo cinfo where cinfo.customerid=vatin.customerid) as 'customername', TotalAmount as 'TotalAmount',totaldiscount,TotalVat as 'Vat',Totalinvoice as 'TotalInvoice',paymenttype  from vatcollection vatin where vatin.invoicedate BETWEEN ? AND ? ";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    // datatbl.setModel(DbUtils.resultSetToTableModel(rs));

                    while (rs.next()) {
                        String invoiceNo = rs.getString("InvoiceNo");
                        String invoicedate = rs.getString("InvoiceDate");
                        String customername = rs.getString("customername");
                        double amount = rs.getDouble("TotalAmount");
                        double discount = rs.getDouble("totaldiscount");
                        double vat = rs.getDouble("vat");
                        double totalinvoice = rs.getDouble("TotalInvoice");
                        String paymenttype = rs.getString("paymenttype");

                        tree++;
                        model2.addRow(new Object[]{tree, invoiceNo, invoicedate, customername, amount, discount, vat, totalinvoice, paymenttype});

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(TotalVat) as 'Total', sum(TotalAmount) as 'totalamt', sum(Totalinvoice) as 'nettotal',sum(totaldiscount) as 'totaldiscount'  from vatcollection vatin where vatin.invoicedate BETWEEN ? AND ? ";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    while (rs.next()) {
                        double totalamt = rs.getDouble("totalamt");
                        String totalamts = String.format("%.2f", totalamt);
                        totalamnt.setText(totalamts);
                        double Totalvat = rs.getDouble("Total");
                        String Totalvats = String.format("%.2f", Totalvat);
                        totalvattext.setText(Totalvats);

                        double nettotal = rs.getDouble("nettotal");
                        String nettotals = String.format("%.2f", nettotal);
                        netotaltext.setText(nettotals);
                        String totaldiscount = rs.getString("totaldiscount");
                        discountext.setText(totaldiscount);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                break;
            case 2:

                try {
                    int tree = 0;
                    DefaultTableModel model2 = (DefaultTableModel) datatbl.getModel();
                    model2.setRowCount(0);
                    String sql = "Select purchaseCode as 'ParcheseCode', (select supliyername from suplyierinfo sinfo where sinfo.id=par.supliyer) as 'CustomerName',DATE_FORMAT(pdate, '%d-%m-%Y') as 'InputDate', Totalrate as 'TotalRate',totaldiscount,totalvat as 'vat',nettotal as 'NetTotal'  from purchase par  where  par.pdate BETWEEN ? AND ? AND par.GRNstatus=1";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    //datatbl.setModel(DbUtils.resultSetToTableModel(rs));
                    while (rs.next()) {
                        String invoiceNo = rs.getString("ParcheseCode");
                        String InputDate = rs.getString("InputDate");
                        String customername = rs.getString("CustomerName");
                        double amount = rs.getDouble("TotalRate");
                        double discount = rs.getDouble("totaldiscount");
                        double vat = rs.getDouble("vat");
                        double totalinvoice = rs.getDouble("NetTotal");
                        String paymenttype = " ";

                        tree++;
                        model2.addRow(new Object[]{tree, invoiceNo, InputDate, customername, amount, discount, vat, totalinvoice, paymenttype});

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(totalvat) as 'Total', sum(Totalrate) as 'totalamt', sum(nettotal) as 'nettotal',sum(totaldiscount) as 'totaldiscount'   from purchase par where  par.pdate BETWEEN ? AND ? AND par.GRNstatus=1 ";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, ((JTextField) fromdatepayment.getDateEditor().getUiComponent()).getText());
                    pst.setString(2, ((JTextField) todatepayment.getDateEditor().getUiComponent()).getText());
                    rs = pst.executeQuery();
                    while (rs.next()) {
                        double totalamt = rs.getDouble("totalamt");
                        String totalamts = String.format("%.2f", totalamt);
                        totalamnt.setText(totalamts);
                        double Totalvat = rs.getDouble("Total");
                        String Totalvats = String.format("%.2f", Totalvat);
                        totalvattext.setText(Totalvats);

                        double nettotal = rs.getDouble("nettotal");
                        String nettotals = String.format("%.2f", nettotal);
                        netotaltext.setText(nettotals);
                        String totaldiscount = rs.getString("totaldiscount");
                        discountext.setText(totaldiscount);

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }

                break;
            default:
                totalamnt.setText(null);
                totalvattext.setText(null);
                netotaltext.setText(null);
                DefaultTableModel model2 = (DefaultTableModel) datatbl.getModel();
                model2.setRowCount(0);
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String fromdate = ((JTextField) fromdatepayment.getDateEditor().getUiComponent()).getText();
        String todate = ((JTextField) todatepayment.getDateEditor().getUiComponent()).getText();

        if (((JTextField) fromdatepayment.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) fromdatepayment.getDateEditor().getUiComponent()).getText().isEmpty() || typebox.getSelectedIndex() == 0) {
            JOptionPane.showConfirmDialog(null, "Please Select Requirment Field", "Requirment", JOptionPane.CANCEL_OPTION);
        } else {
            switch (typebox.getSelectedIndex()) {
                case 1:
                    try {

                        //  int total = Integer.parseInt(AllTotalText.getText());
                        //String inwords = convert(total) + " Tk only";
                        JasperDesign jd = JRXmlLoader.load(new File("")
                                .getAbsolutePath()
                                + "/src/Report/Vat.jrxml");
                        //    JasperDesign jd = JRXmlLoader.load("C:\\Users\\adnan\\Documents\\NetBeansProjects\\MobileInvoice\\src\\Riport\\voiceriport.jrxml");

                        HashMap para = new HashMap();
                        para.put("fromdate", fromdate);
                        para.put("todate", todate);

                        JasperReport jr = JasperCompileManager.compileReport(jd);
                        JasperPrint jp = JasperFillManager.fillReport(jr, para, conn);
                        JasperViewer.viewReport(jp, false);

                    } catch (NumberFormatException | JRException ex) {

                        JOptionPane.showMessageDialog(null, ex);

                    }
                    break;
                case 2:
                    try {

                        //  int total = Integer.parseInt(AllTotalText.getText());
                        //String inwords = convert(total) + " Tk only";
                        JasperDesign jd = JRXmlLoader.load(new File("")
                                .getAbsolutePath()
                                + "/src/Report/vatcollectionpr.jrxml");
                        //    JasperDesign jd = JRXmlLoader.load("C:\\Users\\adnan\\Documents\\NetBeansProjects\\MobileInvoice\\src\\Riport\\voiceriport.jrxml");

                        HashMap para = new HashMap();
                        para.put("fromdate", fromdate);
                        para.put("todate", todate);

                        JasperReport jr = JasperCompileManager.compileReport(jd);
                        JasperPrint jp = JasperFillManager.fillReport(jr, para, conn);
                        JasperViewer.viewReport(jp, false);

                    } catch (NumberFormatException | JRException ex) {

                        JOptionPane.showMessageDialog(null, ex);

                    }
                    break;
                default:
                    break;
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void typeboxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_typeboxPopupMenuWillBecomeInvisible

        switch (typebox.getSelectedIndex()) {
            case 1:
                try {
                    int tree = 0;
                    DefaultTableModel model2 = (DefaultTableModel) datatbl.getModel();
                    model2.setRowCount(0);
                    String sql = "Select invoiceNopurchaseNo as 'InvoiceNo',DATE_FORMAT(invoicedate, '%d-%m-%Y') as 'InvoiceDate',(select customername from customerinfo cinfo where cinfo.customerid=vatin.customerid) as 'customername', TotalAmount as 'TotalAmount',totaldiscount,TotalVat as 'Vat',Totalinvoice as 'TotalInvoice',paymenttype  from vatcollection vatin";
                    pst = conn.prepareStatement(sql);

                    rs = pst.executeQuery();
                    // datatbl.setModel(DbUtils.resultSetToTableModel(rs));

                    while (rs.next()) {
                        String invoiceNo = rs.getString("InvoiceNo");
                        String invoicedate = rs.getString("InvoiceDate");
                        String customername = rs.getString("customername");
                        double amount = rs.getDouble("TotalAmount");
                        double vat = rs.getDouble("vat");
                        double totalinvoice = rs.getDouble("TotalInvoice");
                        double discount = rs.getDouble("totaldiscount");
                        String paymenttype = rs.getString("paymenttype");

                        tree++;
                        model2.addRow(new Object[]{tree, invoiceNo, invoicedate, customername, amount, discount, vat, totalinvoice, paymenttype});

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(TotalVat) as 'Total', sum(TotalAmount) as 'totalamt', sum(Totalinvoice) as 'nettotal',sum(totaldiscount) as 'totaldiscount'  from vatcollection ";
                    pst = conn.prepareStatement(sql);

                    rs = pst.executeQuery();
                    while (rs.next()) {
                        double totalamt = rs.getDouble("totalamt");
                        String totalamts = String.format("%.2f", totalamt);
                        totalamnt.setText(totalamts);
                        double Totalvat = rs.getDouble("Total");
                        String Totalvats = String.format("%.2f", Totalvat);
                        totalvattext.setText(Totalvats);
                        double nettotal = rs.getDouble("nettotal");
                        String nettotals = String.format("%.2f", nettotal);
                        netotaltext.setText(nettotals);
                        String totaldiscount = rs.getString("totaldiscount");
                        discountext.setText(totaldiscount);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                break;
            case 2:

                try {
                    int tree = 0;
                    DefaultTableModel model2 = (DefaultTableModel) datatbl.getModel();
                    model2.setRowCount(0);
                    String sql = "Select purchaseCode as 'ParcheseCode', (select supliyername from suplyierinfo sinfo where sinfo.id=par.supliyer) as 'CustomerName',DATE_FORMAT(pdate, '%d-%m-%Y') as 'InputDate', Totalrate as 'TotalRate',totaldiscount,totalvat as 'vat',nettotal as 'NetTotal'  from purchase par  where  par.GRNstatus=1";
                    pst = conn.prepareStatement(sql);

                    rs = pst.executeQuery();
                    //datatbl.setModel(DbUtils.resultSetToTableModel(rs));
                    while (rs.next()) {
                        String invoiceNo = rs.getString("ParcheseCode");
                        String InputDate = rs.getString("InputDate");
                        String customername = rs.getString("CustomerName");
                        double amount = rs.getDouble("TotalRate");
                        double discount = rs.getDouble("totaldiscount");
                        double vat = rs.getDouble("vat");
                        double totalinvoice = rs.getDouble("NetTotal");
                        String paymenttype = " ";
                        tree++;
                        model2.addRow(new Object[]{tree, invoiceNo, InputDate, customername, amount, discount, vat, totalinvoice, paymenttype});

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try {
                    String sql = "Select sum(totalvat) as 'Total', sum(Totalrate) as 'totalamt', sum(nettotal) as 'nettotal', sum(totaldiscount) as 'totaldiscount'   from purchase where  GRNstatus=1 ";
                    pst = conn.prepareStatement(sql);

                    rs = pst.executeQuery();
                    while (rs.next()) {
                        double totalamt = rs.getDouble("totalamt");
                        String totalamts = String.format("%.2f", totalamt);
                        totalamnt.setText(totalamts);
                        double Totalvat = rs.getDouble("Total");
                        String Totalvats = String.format("%.2f", Totalvat);
                        totalvattext.setText(Totalvats);
                        double nettotal = rs.getDouble("nettotal");
                        String nettotals = String.format("%.2f", nettotal);
                        netotaltext.setText(nettotals);
                        String totaldiscount = rs.getString("totaldiscount");
                        discountext.setText(totaldiscount);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }

                break;
            default:
                totalamnt.setText(null);
                totalvattext.setText(null);
                netotaltext.setText(null);
                DefaultTableModel model2 = (DefaultTableModel) datatbl.getModel();
                model2.setRowCount(0);
                break;
        }
    }//GEN-LAST:event_typeboxPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable datatbl;
    private javax.swing.JLabel discountext;
    private com.toedter.calendar.JDateChooser fromdatepayment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel netotaltext;
    private com.toedter.calendar.JDateChooser todatepayment;
    private javax.swing.JLabel totalamnt;
    private javax.swing.JLabel totalvattext;
    private javax.swing.JComboBox<String> typebox;
    // End of variables declaration//GEN-END:variables
}
